import Head from 'next/head';
// import Image from 'next/image';
import Layout from '../components/Layout';

export default function Home(props) {
  return (
    <Layout>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1 /*  className={props.styles.title} */>
        Welcome to <a href="https://ecommerce-2022.herokuapp.com/">Shop!</a>
      </h1>
      {JSON.stringify(props)}
    </Layout>
  );
}
